services:
  sgcc_electricity_app:
    # GHCR 镜像（推荐）
    image: ghcr.io/poiig/sgcc_electricity:latest
    # GHCR 南京大学镜像加速（国内推荐）
    # image: ghcr.nju.edu.cn/poiig/sgcc_electricity:latest
    # Docker Hub 镜像
    # image: poiigzhao/sgcc_electricity:latest
    # Docker Hub 镜像加速
    # image: docker.1ms.run/poiigzhao/sgcc_electricity:latest
    container_name: sgcc_electricity
    env_file:
      - .env
    environment:
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=Asia/Shanghai
      - PYTHON_IN_DOCKER=PYTHON_IN_DOCKER
      - ENV_FILE=/data/.env
      - WEB_DASHBOARD=true
      - WEB_DASHBOARD_PORT=8080
    ports:
      - 8080:8080
    restart: unless-stopped
    volumes:
      - ./data:/data
      - ./.env:/data/.env
    init: true
